/**
 * WalmartItem
 * Walmart Item Module
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import CollectorRequests  from '../../src/api/CollectorRequests';
import CollectorEvents  from '../../src/api/CollectorEvents';

describe('CollectorApi', function(){
  let requests;
  let events;
  beforeEach(function() {
    requests = new CollectorRequests({
        registerHandler(){
        },
        sendRequest(){
        }
    });
    events = new CollectorEvents({
        registerEventListener(){
        },
        emitEvent(){
        }
    });

  });


    describe('addItem', function() {
      it('should send request addItem successfully', ()=> {
        //uncomment below and update the code to test addItem
        //return requests.addItem(item: any).then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

    describe('itemAdded', function() {
        it('should emit event itemAdded successfully', (done)=> {
        //uncomment below and update the code to test itemAdded
        //register listener.
        //events.addItemAddedEventListener(()=>done());
        //emit event.
        //events.emitItemAdded(itemId: string);
        //});
        done();
        });
    });

    describe('postEvent', function() {
      it('should send request postEvent successfully', ()=> {
        //uncomment below and update the code to test postEvent
        //return requests.postEvent(opts: any).then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

});
